### ISSUE TITLE
Fake model

### ISSUE THREAD

**Issue by alakhirnayan** [mrkolarik/3D-brain-segmentation#10]
It's a fake model. 
Full of error and I think it does not run.

**Comment by mrkolarik** [comment]
Hi Alakhirnayn,

our implementation has been used successfully in many publications (currently has over 40 citation) for example here [LINK](https://www.nature.com/articles/s41598-021-01296-1). Due to your rude comment, I will not try to help you with your implementation and I will close this issue now.

Take care,

Martin
