### ISSUE TITLE
Some Details in Paper

### ISSUE THREAD

**Issue by Fuzhiyuan** [mrkolarik/3D-brain-segmentation#12]
on the paper ,table2, strides is (0,0,0)? that is mean stride =1? and do you use bn or other normalization?

**Comment by mrkolarik** [comment]
Hi @Fuzhiyuan,

thanks for the questions. You can find the reference architecture here on GitHub, and yes, table 2 should better state (1, 1, 1) instead of (0, 0, 0). I guess I somehow wrongly meant that as "default stride value".
The network we used for this research did not contain any batch normalization layers as it was optimized for large feature size and used batch_size=1. Other normalization methods were not considered at that time (we started working on this already more than four years ago :D )

Best regards,

Martin
