### ISSUE TITLE
What is the definition of the "total"?

### ISSUE THREAD

**Issue by Heinrich-125652** [mrkolarik/3D-brain-segmentation#14]
Thank you so much for sharing this fantastic source code.
I have a couple of inquiries:

Could you please clarify the meaning of "total" in both line 21 and line 129 of the "data3D.py" file?
Specifically, I'm seeking an explanation for the relevance of the values 16, 2, and 18.

Additionally, the paper highlights the utilization of 8-bit PNG images.
Hence, I'm curious about the rationale behind setting the "image_depth" in the code to 16.

I am aware of your busy schedule and sincerely value your guidance.

**Comment by mrkolarik** [comment]
Hello,

Thank you for your comment, and I am happy this project can still contribute to someone's research endeavours. To you questions:

- variable "total" contains the "total" number of images as they are loaded as individual images from folders containing scan of each patient. The numbers 16, 2 and 18 should divide the dataset manually to training and testing sets, however, I do not remember exactly the number of slices of each scan. I have to say I am sorry the code is not better formatted and contains a lot of unexplained numbers for loading the dataset, however, we did not think anybody would actually be using it. Due to the continuation of citations even to this day, I should do a revised version.
- The image_depth variable denotes the depth size of the input feature 16x400x400 in the case of brain images - it is not a bit-depth.

Hope this helps and sorry for the messy code once again!

Martin
