### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'theano'

### ISSUE THREAD

**Issue by FahadMahdi** [mrkolarik/3D-brain-segmentation#6]
I am trying to calculate the dice coefficient using 2D-unet, however, I am getting the following error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "E:/2.U_Net_Humerus_Segmentation/U-Net/3D-brain-segmentation-master/2D-unet.py", line 235, in <module>
    compare()
  File "E:/2.U_Net_Humerus_Segmentation/U-Net/3D-brain-segmentation-master/2D-unet.py", line 226, in compare
    K.theano.shared(y_true),
AttributeError: module 'keras.backend' has no attribute 'theano'

**Comment by mrkolarik** [comment]
Hi FahadMahdi,

your problem is in the fact you apparently used some code from a repository using theano backend and added it to mine as the original file 2D-unet.py in this repository has only 203 lines and your error is on lines 235 and 226. I suggest you to find tensorflow implementation for you problem.

Take care,

mrkolarik

**Comment by FahadMahdi** [comment]
Hi Kolarik,

Thank you very much for your reply.

I am sorry for the late reply.

Due to the state of emergency, our lab is now closed.

I will study on your suggestion.

Thank you.
Best regards
*------------------------------*
*Fahad Parvez Mahdi*
PhD Student
